import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    alignItems: "center",
    marginTop: 75,
  },
  title: {
    width: "90%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  textTitle: {
    fontSize: 16,
    fontWeight: "bold",
  },
  containerContact: {
    backgroundColor: "#CF9F69",
    width: 64,
    height: 64,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 32,
    marginTop: 32,
    marginBottom: 16,
  },
  inputSmall: {
    width: "90%",
    height: 45,
    marginBottom: 8,
    backgroundColor: "#CF9F69",
    borderRadius: 15,
    borderColor: "#382e1e",
    borderWidth: 1.5,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.32,
    shadowRadius: 5.46,
    elevation: 9,
  },
  placeholder: {
    fontSize: 16,
    marginLeft: 10,
    color: "#382e1e",
  },
  inputBig: {
    width: "90%",
    height: 115,
    marginBottom: 8,
    backgroundColor: "#CF9F69",
    borderRadius: 15,
    borderColor: "#382e1e",
    borderWidth: 1.5,
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "space-around",
    paddingVertical: 12,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.32,
    shadowRadius: 5.46,
    elevation: 9,
  },
  select: {
    flexDirection: "row",
    width: "90%",
    justifyContent: "space-between",
    alignItems: "center",
  },
  containerPicker: {
    justifyContent: "center",
    borderWidth: 5,
    borderRadius: 15,
    width: "65%",
    height: 50,
    borderColor: "#382e1e",
    backgroundColor: "#CF9F69",
    paddingLeft: 16,
  },
  textBold: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#382E1E",
  },
  field: {
    marginTop: 15,
  },
  add: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#0645AD",
  },
  centeredView: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
    marginTop: 22,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    marginBottom: 30,
  },
  modalView: {
    width: "100%",
    height: 350,
    backgroundColor: "white",
    borderTopRightRadius: 25,
    borderTopLeftRadius: 25,
    padding: 35,
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  modalText: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 60,
    textAlign: "center",
  },
  textImage: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  textStyle: {
    fontSize: 14,
    fontWeight: "bold",
    textAlign: "left",
    marginBottom: 30,
  },
});

export default styles;
